include:
  - project: 'templates/ci'
    file: 'DockerInDockerTemplate.yml'

variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

stages:
- build
- test

build-backend:
  stage: build
  image: golang:latest
  script:
   - cd backend
   - mkdir app
   - go build -o app ./...
   - ls -al app 
   - mkdir momo-store-${VERSION}
   - ls -al momo-store-${VERSION}
   - mv app/api momo-store-${VERSION}/api-${VERSION}
   - ls -al momo-store-${VERSION}
  artifacts:
    paths:
    - ${CI_PROJECT_DIR}/backend/momo-store-${VERSION}/api-${VERSION}

sonarq-backend-check:
  stage: test
  dependencies:
    - build-backend
  image: sonarsource/sonar-scanner-cli
  variables:
    SONAR_TOKEN: "b57503060240d9bd248e9803af43d0cf2810f04c"
    SONAR_HOST_URL: "https://sonarqube.praktikum-services.ru"
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  script:
    - cd backend
    -  sonar-scanner \
      -Dsonar.projectKey=02_alexander_volokhov_backend_momo \
      -Dsonar.host.url=https://sonarqube.praktikum-services.ru \
      -Dsonar.login=b57503060240d9bd248e9803af43d0cf2810f04c

  allow_failure: true