include:
  - project: 'templates/ci'
    file: 'DockerInDockerTemplate.yml'

variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

stages:
- build
- test

build-backend:
  stage: build
  image: golang:latest
  script:
   - cd backend
   - mkdir app
   - go build -o app ./...
   - ls -al app 
   - mkdir momo-store-${VERSION}
   - ls -al
   - mv app/api momo-store-${VERSION}/api-${VERSION}
   - ls -al
  
  artifacts:
    paths:
    - ${CI_PROJECT_DIR}/backend/momo-store-${VERSION}/api-${VERSION}
    - ${MAVEN_REPO_PATH}
