include:
  - project: 'templates/ci'
    file: 'DockerInDockerTemplate.yml'

variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

stages:
- build

build-backend:
  stage: build
  image: golang:latest
  script:
   - cd backend
   - mkdir app
   - go build -o app ./...